<?php

namespace ContainerGWuW2Ws;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHksNKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cHks_nK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cHks_nK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidatureRepository' => ['privates', 'App\\Repository\\CandidatureRepository', 'getCandidatureRepositoryService', true],
            'qrCodeGenerator' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
        ], [
            'candidatureRepository' => 'App\\Repository\\CandidatureRepository',
            'qrCodeGenerator' => 'App\\Service\\QrCodeService',
        ]);
    }
}
