<?php

namespace ContainerGWuW2Ws;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9xkrw2CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9xkrw2C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9xkrw2C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'emailService' => 'App\\Service\\EmailService',
            'entityManager' => '?',
            'slugger' => '?',
            'userPasswordHasher' => '?',
        ]);
    }
}
