<?php

namespace ContainerGWuW2Ws;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4eEsDc4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4eEsDc4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4eEsDc4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'user' => ['privates', '.errored..service_locator.4eEsDc4.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.4eEsDc4": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pdfService' => 'App\\Service\\PdfService',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
