framework:
    secret: '1234567890abcdef1234567890abcdef'
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: false
        cookie_samesite: lax
        cookie_lifetime: 3600
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true

    php_errors:
        log: true

    validation: { enable_annotations: true }
    csrf_protection: true
    form: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
