<?php

namespace ContainerXIO77pY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YOaq1AbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YOaq1Ab' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YOaq1Ab'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidatureRepository' => ['privates', 'App\\Repository\\CandidatureRepository', 'getCandidatureRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'missionRepository' => ['privates', 'App\\Repository\\MissionRepository', 'getMissionRepositoryService', true],
        ], [
            'candidatureRepository' => 'App\\Repository\\CandidatureRepository',
            'em' => '?',
            'missionRepository' => 'App\\Repository\\MissionRepository',
        ]);
    }
}
