<?php

namespace ContainerXIO77pY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6JwLcoIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6JwLcoI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6JwLcoI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'logger' => ['privates', 'logger', 'getLoggerService', false],
            'user' => ['privates', '.errored..service_locator.6JwLcoI.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.6JwLcoI": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'logger' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
