<?php

namespace ContainerXIO77pY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0TmC_XuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0TmC.Xu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0TmC.Xu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'twilioService' => ['privates', 'App\\Service\\TwilioService', 'getTwilioServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'twilioService' => 'App\\Service\\TwilioService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
