<?php

namespace ContainerXIO77pY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PdfService' shared autowired service.
     *
     * @return \App\Service\PdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PdfService.php';

        return $container->privates['App\\Service\\PdfService'] = new \App\Service\PdfService();
    }
}
