<?php

namespace ContainerXIO77pY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserRegistrationEmailListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\UserRegistrationEmailListener' shared autowired service.
     *
     * @return \App\EventListener\UserRegistrationEmailListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/UserRegistrationEmailListener.php';

        $a = ($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService'));

        if (isset($container->privates['App\\EventListener\\UserRegistrationEmailListener'])) {
            return $container->privates['App\\EventListener\\UserRegistrationEmailListener'];
        }

        return $container->privates['App\\EventListener\\UserRegistrationEmailListener'] = new \App\EventListener\UserRegistrationEmailListener($a, ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
