<?php

namespace ContainerDsExuyy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SrW5kY7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SrW5kY7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SrW5kY7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'pdfService' => 'App\\Service\\PdfService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
