<?php

namespace ContainerDsExuyy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7WvtqbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i7Wvtqb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i7Wvtqb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidature' => ['privates', '.errored..service_locator.i7Wvtqb.App\\Entity\\Candidature', NULL, 'Cannot autowire service ".service_locator.i7Wvtqb": it needs an instance of "App\\Entity\\Candidature" but this type has been excluded in "config/services.yaml".'],
            'qrCodeService' => ['privates', 'App\\Service\\QrCodeService', 'getQrCodeServiceService', true],
        ], [
            'candidature' => 'App\\Entity\\Candidature',
            'qrCodeService' => 'App\\Service\\QrCodeService',
        ]);
    }
}
