<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGWuW2Ws\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGWuW2Ws/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGWuW2Ws.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGWuW2Ws\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGWuW2Ws\App_KernelDevDebugContainer([
    'container.build_hash' => 'GWuW2Ws',
    'container.build_id' => 'd186dc04',
    'container.build_time' => 1746225723,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGWuW2Ws');
